POST http://localhost:8080/api/studentLogin
Content-Type: application/json

{
  "studentNumber": 2017214216
}

###
POST http://localhost:8080/api/student/index
Content-Type: application/json
Authorization: {{token}}

{
    "directions": [1,2,3,4]
}

###
PATCH http://localhost:8080/api/student/student
Authorization: {{token}}
Content-Type: application/json

{
 "teacherId": 6
}

###
GET http://localhost:8080/api/teacher/index
Accept: application/json
Authorization: {{token}}

###
POST http://localhost:8080/api/teacher/student
Content-Type: application/json
Authorization: {{token}}

{
  "name": "xp",
  "number": 201701
}

###
POST http://localhost:8080/api/teacher/selectNumber
Content-Type: application/json
Authorization: {{token}}

{
  "selectNumber": 8
}

###
POST http://localhost:8080/api/teacher/ranges
Content-Type: application/json
Authorization: {{token}}

{
  "ranges": 12
}

###
POST http://localhost:8080/api/teacher/password
Content-Type: application/json
Authorization: {{token}}

{
  "password" : "1314"
}

###
POST http://localhost:8080/api/teacher/courses
Content-Type: application/json
Authorization: {{token}}

{
  "name" :"Web"
}

###
POST http://localhost:8080/api/teacherLogin
Content-Type: application/json

{
  "number" : "2017",
  "password": "2017"
}


> {% client.global.set("token", response.headers.valueOf("Authorization")); %}
###